# Generated by Django 5.2.8 on 2026-02-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='role',
        ),
        migrations.AddField(
            model_name='usertype',
            name='is_curator',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a curator or a harvester'),
        ),
    ]
