# Generated by Django 5.2.11 on 2026-02-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_upload_url_alter_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(default='placeholder', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
